### ISSUE TITLE
[Bug]: Thonkutil breaks drawer model 

### ISSUE THREAD

**Issue by ClaudiusMinimus** [MattiDragon/ExtendedDrawers#30]
### Description of the issue

I am in the process of updating my pack Create on a Potato PC and would like to use your mod, All three drawers have broken textures as shown in the screenshots shown below.

### Reproduction steps

1. Open REI and search for @drawer
2. View broken textures
3. Craft a drawer and see broken texture
4. Place to see broken texture

### Mod version

ExtendedDrawers-1.3.4+mc.1.18.2.jar

### Operating System

Linux Mint 20.3

### Minecraft version

1.18.2

### Other mods

1.18.2-StorageCabinet-1.4.3
AdditionalAdditions-4.0.5
All Arrows Infinity Fix-FABRIC-1.0.0-MC-1.18
appleskin-fabric-mc1.18.2-2.4.1
architects-palette-fabric-2.2
architectury-4.9.84-fabric
autoconfig1u-3.4.0
auudio_fabric_1.0.3_MC_1.18-1.18.2
balm-fabric-3.2.0+0
betterCompatibilityChecker-fabric-1.0.5
bobby-3.1.1
Bookshelf-Fabric-1.18.2-13.2.50
Botania-1.18.2-435-FABRIC
BuildingWands_mc1.18.2-2.6.3_release-fabric
camerautils-1.18.2-1.0.1
chisel-1.4.5+1.18.x
cloth-config-6.2.57-fabric
Clumps-fabric-1.18.2-8.0.0+15
comforts-fabric-1.1.3-1.18.2
continuity-2.0.1+1.18.2
Couplings-1.8.1+1.18.2
craftingtweaks-fabric-1.18.2-14.0.3
create-fabric-1.18.2-0.5.0e-733
createaddition+1.18.2-20220914a
createplus-1.0.0-beta4
cullleaves-2.3.2
dankstorage-1.18.2-3.7.1
dark-enchanting-1.0.0+1.18.2
deepslatecutting-1.18.2-1.3.4
drippyloadingscreen_fabric_1.6.4_MC_1.18-1.18.2
DynamicSoundFilters-1.3.0+1.18.2
EditSign-1.18.2-2.3.1
ellemes-container-library-2.1.0-alpha.12+1.18.2-fabric
EmeraldTools-Fabric-1.18.2-1.3.48
EnchantmentDescriptions-Fabric-1.18.2-10.0.9
essential_commands-0.24.5-mc1.18.2
EssentialGUI-1.7.3+1.18.2
ExtendedDrawers-1.3.4+mc.1.18.2
extremesoundmuffler-3.29_fabric-1.18.2
fabric-api-0.59.0+1.18.2
fabric-branders-spawnermod-1.18.2-1.1.2
fabric-language-kotlin-1.8.4+kotlin.1.7.20
fabric-language-scala-1.1.0+scala.2.13.6-fat
fancymenu_fabric_2.12.2_MC_1.18.2
farmers-delight-fabric-1.18.2-1.2.1
farmingforblockheads-fabric-1.18.2-10.0.2
feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1
ftb-chunks-fabric-1802.3.6-build.170
ftb-library-fabric-1802.3.6-build.140
ftb-quests-fabric-1802.3.8-build.106
ftb-ranks-fabric-1802.1.8-build.34
ftb-teams-fabric-1802.2.6-build.69
geckolib-fabric-1.18-3.0.64
graves-2.0.3+1.18.2
GreaterEye-Fabric-1.18.2-1.3.25
grind-enchantments-1.6.4+1.18.2
grizzlybear-1.18-1.3
here-be-no-dragons-1.0.0
indium-1.0.7+mc1.18.2
IronChests-1.7.4
item-filters-fabric-1802.2.7-build.21
jam-lib-0.0.5
justenoughkeys-0.5.3-fabric
keywizard-fabric-v2.0.1
kibe-1.9.10-BETA+1.18
konkrete_fabric_1.5.0_MC_1.18-1.18.2
kubejs-fabric-1802.5.5-build.550
lambdynamiclights-2.1.0+1.17
leaves-us-in-peace-1.0.11+MC1.18.2
light-overlay-6.0.5
mcpitanlibarch-1.0.8-1.18-fabric
MiningDimensions_Fabric-1.18.2-1.3.9
Mo-Glass-1.6.1-MC1.18.2
MobCatcher-Fabric-1.18.2-1.1.29
modmenu-3.2.3
ModularLootCrates-3.2.0-1.18.1
MoreGems-Fabric-1.18.2-1.3.71
MouseTweaks-fabric-mc1.18-2.22
mousewheelie-1.10.2+mc1.18.2
mythic-mounts-1.18.2-7.0
NE-1.18-Fabric-1.4.0
OverpoweredPickles-Fabric-1.18.2-1.3.14
Patchouli-1.18.2-71.1-FABRIC
phosphor-fabric-mc1.18.x-0.8.1
polymorph-fabric-0.0.21-1.18.2
projectsavethepets-3.1.0-old.1.18+2022.10af157d70.fabric
quartz-elevator-2.1.2+1.18.2
reeses_sodium_options-1.4.7+mc1.18.2-build.58
repurposed_structures_fabric-4.1.14+1.18.2
ResourcefulTools-Fabric-1.18.2-1.2.38
rhino-fabric-1802.2.1-build.240
rightclickharvest-3.0.1+1.18
RoughlyEnoughItems-8.3.549
shulkerboxtooltip-fabric-3.1.2+1.18.2
SimpleBackpack_Fabric-1.18.2-1.2.37
sodium-extra-0.4.11+mc1.18.2-build.67
sodium-fabric-mc1.18.2-0.4.1+build.15
textile_backup-2.4.0-1.18
The_Graveyard_1.9_(FABRIC)_for_1.18.2
thonkutil-2.14.1+1.18
toms_storage_fabric-1.18.2-1.4.3
trinkets-3.3.1
UncraftingTable-fabric-1.1.0
WardBlocks-Fabric-1.18.2-1.2.28
waystones-fabric-1.18.2-10.1.0
wmitaf-fabric-mc1.18.2-2.4.0
wraith-harvestscythes-2.5.1
Xaeros_Minimap_22.15.1_Fabric_1.18.2
XaerosWorldMap_1.28.0_Fabric_1.18.2
YungsApi-1.18.2-Fabric-2.0.8

### Server

Not tested

### Client

Happens

### Logs

https://mclo.gs/UbdpFkK

### Extra Context

![image](https://user-images.githubusercontent.com/17887664/195670524-9b326e93-124a-4808-8b44-d27bd1d4b428.png)

![image](https://user-images.githubusercontent.com/17887664/195670660-50e3251c-15e8-4ea2-a47f-d56e571d81bf.png)

**Comment by MattiDragon** [comment]
Are all those mods required to reproduce the issue? I don't think so. Could you find a minimum set of mods required?

**Comment by ClaudiusMinimus** [comment]
You should be able to reproduce it with the following:

- architectury-4.9.84-fabric.jar
- cloth-config-6.2.57-fabric.jar
- ExtendedDrawers-1.3.4+mc.1.18.2.jar
- fabric-api-0.59.0+1.18.2.jar
- RoughlyEnoughItems-8.3.549.jar
- thonkutil-2.14.1+1.18.jar

[ThionkUtil](https://www.curseforge.com/minecraft/mc-mods/thonkutil) is a dependency of [Goblin Traders](https://www.curseforge.com/minecraft/mc-mods/goblin-traders-fabric/files/3717825), which I dropped from the pack - I had forgotten to remove ThionkUtil. Out of curiosity, I add Goblin Traders and the texture was still broken. As far as I am concerned I this issue is fixed for me, but if someone else uses Goblin Traders, then you will have the same issue. I hope this helps you.

Thank you,
CM

**Comment by ClaudiusMinimus** [comment]
BTW with ThonkUtil removed the textures are fixed!
![image](https://user-images.githubusercontent.com/17887664/196009214-1cd644d1-ed64-4317-b159-90b0df91e9b1.png)
![image](https://user-images.githubusercontent.com/17887664/196009253-ab69b7a8-b9ae-4586-94d6-deac90a8a512.png)

**Comment by MattiDragon** [comment]
Reopening. Thonkutil breaking the mod is still an issue. I'll have to see why it happens

**Comment by MattiDragon** [comment]
Thonkutil assumes things it shouldn't, breaking extended drawers when it breaks those assumptions

**Comment by MattiDragon** [comment]
Seems like they fixed it, closing

**Comment by Shandoo94** [comment]
I could just confirm that this is still an issue on  MC 1.19.2 fabric 0.14.11 with Extended Drawers 1.3.5 and Thonkutil 2.15.4

**Comment by Mg138** [comment]
Still happens with goblin-traders-1.5.2 / thonkutil-2.15.4+1.19

**Comment by Mg138** [comment]
Actually, this looks different.

**Comment by zweikommensteuer** [comment]
I still have this issue on MC 1.19.2 / Fabric 0.14.19 when using:

cloth-config-8.2.88-fabric
configured-fabric-2.0.0-1.19.2
ExtendedDrawers-1.3.9+mc.1.19.2
fabric-api-0.76.0+1.19.2
goblintraders-fabric-1.8.1-1.19.2
thonkutil-2.15.4+1.19

any ideas?

**Comment by MattiDragon** [comment]
Could you open another issue? It's probably a new bug
